footprint: [[1,0.4], [-1,0.4], [-1,-0.4], [1,0.4]]
# robot_radius: 0.2 # distance a circular robot should be clear of the obstacle
inflation_radius: 0.5
transform_tolerance: 10
observation_sources: laser_scan_sensor #point_cloud_sensor

obstacle_range: 2.5
raytrace_range: 4.0

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

# inflation_layer:
#   enabled:              true
#   cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
#   inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

#   obstacle_layer:
#     enabled:              true
#     unknown_threshold:    15
#     mark_threshold:       0
#     combination_method:   0
#     track_unknown_space:  true    #true needed for disabling global path planning through unknown space
#     obstacle_range: 2.5
#     raytrace_range: 3.0



